### ISSUE TITLE
Bad Doom 3 .map output with Blender 3.4.1

### ISSUE THREAD

**Issue by motorsep** [c-d-a/io_export_qmap#7]
I am getting this error in Dark Radiant when importing simple 64x64x64 cube map :(
![image](https://user-images.githubusercontent.com/1927918/211464572-1c1c0d0f-d218-4a91-a07e-e962ababdb8b.png)

Exported map and reference map are attached,
[Blender_Doom3_testmap.zip](https://github.com/c-d-a/io_export_qmap/files/10378974/Blender_Doom3_testmap.zip)

Export settings I used:
![image](https://user-images.githubusercontent.com/1927918/211465142-f9b369c0-cbb5-4ef4-9795-3d7fe397559f.png)

**Comment by c-d-a** [comment]
Select "Quake 2" as the flag format. Doom 3 maps expect empty flags as an atavism. The exporter doesn't default to using them for Q4 compatibility.
I can't check the export right now, but I believe that should be it.

**Comment by motorsep** [comment]
I'll check after work, thanks.

**Comment by motorsep** [comment]
Alright, that worked (DarkRadiant didn't complain). I am only using Brush setting right now.

Something if off with texturing:
![image](https://user-images.githubusercontent.com/1927918/211689660-d15f582a-e3e6-48ae-ae41-bac37d9c5553.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/1927918/211689940-8f848670-bfa1-4216-9c94-b77b24d4909a.png)

How do I need to set up UV in Blender to get the same result right out of the box ?

Also, if you diff the two files, you'll see that add-on adds -0 instead of putting 0 (and I am guessing other numbers are off because of texture coordinates?). 

[Blender_Doom3_testmap2.zip](https://github.com/c-d-a/io_export_qmap/files/10387748/Blender_Doom3_testmap2.zip)

**Comment by c-d-a** [comment]
Your material in Blender doesn't use any texture maps, so the exporter defaults to 64x64. There is no way to get correct UV scale without a reference size, though I suppose I should expose the fallback size in the export dialog and make this aspect clear in the readme.
Currently, the exporter uses the first texture it stumbles upon in the node tree, doesn't have to be base color or even connected to anything. In case you're new to Blender, you add a texture by clicking on a yellow dot next to "Base Color", then pick "Image Texture", then create or pick an existing one (either will do).
Additionally, the default cube in Blender uses a cross-shaped unwrap. If you want each face to occupy the entire UV space, press Tab -> U -> "Reset" -> Tab.

Now, those are the basics. However, it does seem like you found some sort of a bug related to exporting as a brush. Half the faces look normal, but half have bad UVs. Usually this happens when the convex hull operation patches over some concave faces, but it shouldn't affect a basic cube. I'll look into this later today.
![bugged_uvs](https://user-images.githubusercontent.com/55441216/211707485-c79aa47d-2438-433c-bc16-04eab154b437.png)

**Comment by motorsep** [comment]
Here is video of me doing the whole thing:
https://www.youtube.com/watch?v=sY2cpEnBKJw

**Comment by c-d-a** [comment]
Fixed convex hull in https://github.com/c-d-a/io_export_qmap/commit/0f1d518e5e57b085a40549cb91dbce0e897c0614
(reverted to how it used to be in the first version of the exporter; Blender's 'geom_interior' seems unintuitive/bugged)
The process:

https://user-images.githubusercontent.com/55441216/211718579-ccbb0d16-9159-44db-b170-891f1b86400a.mp4

**Comment by c-d-a** [comment]
Exposed the fallback size, made readme changes. Closing.
